version: "3.7"
services:
  api:
    image: rarhaeu/chmura2020:latest
    container_name: rest-api
    restart: always
    networks:
      bridge-zadanie-1:
    ports:
    - "5000:5000"
  mysql:
    image: mysql/mysql-server:8.0
    container_name: full2020-87726
    restart: unless-stopped
    networks:
      bridge-zadanie-1:
        - ipv4_address: 10.0.10.3
    ports:
    - "3306:3306"

networks:
  bridge-zadanie-1:
    external: true
